- name: transfer ngnix.conf.j2
  hosts: all
  become: yes
  gather_facts: no

  vars: 
    src_path: /home/test6/nginx.conf.j2
    dest_path: /etc/nginx/nginx.conf

  tasks:
    - name: transfer file to dest
      #file:      # 改正：下发 j2 必须用 template 模块
      template:
        src: "{{ src_path }}"  # 改正：用引号包起来
        dest: "{{ dest_path }}" # 改正：用引号包起来 改正：dest
        mode: "0644"
      notify: restart nginx service
  
  handlers:
    - name: restart nginx service
      systemd:
        name: nginx
        state: restarted


- name: download and unarchive file
  hosts: all
  become: yes
  gather_facts: no

  vars:
    src_path: /opt/tools

  tasks:
    - name: create /opt/tools
      file:
        path: {{ src_path }}
        state: directory
        mode: 0755

    - name: download file
      #shell: cd /tmp && wget -c -O my-tools-v1.tar.gz "http://192.168.1.100/downloads/my-tools-v1.tar.gz"
      #get_url用它下载，如果文件已经存在且没变化，它就不会重复下载
      get_url:
        url: http://192.168.1.100/downloads/my-tools-v1.tar.gz
        dest: /tmp/my-tools-v1.tar.gz

    - name: unarchive the file
      unarchive:
        src: /tmp/my-tools-v1.tar.gz
        dest: {{ src_path }}
        remote_src: yes     # 关键点：告诉 Ansible 这个包已经在远端机器上了，不要在本地找！
        

- name: install basic network utilization
  host: all
  become: yes
  gather_facts: yes

  tasks:
    # 针对 CentOS / RHEL 家族
    - name: Install network tools for RedHat family
      yum:
        name: "{{ item }}"
        state: present
      # 使用 loop 循环安装这两个包
      loop:
        - net-tools
        - bind-utils
      # 关键点：条件判断！只有系统是 RedHat 时才执行这个任务
      when: ansible_os_family == "RedHat"

    # 针对 Ubuntu / Debian 家族
    - name: Install network tools for Debian family
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - net-tools
        - dnsutils
      # 关键点：条件判断！只有系统是 Debian 时才执行这个任务
      when: ansible_os_family == "Debian"