- name: Enable root SSH and set root password
  hosts: all
  become: yes
  gather_facts: no

  vars:
    root_password: "Goodsense@123"

  tasks:
  
    - name: Enable PermitRootLogin yes
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin.*'
        line: 'PermitRootLogin yes'
        backup: no
      notify: reload sshd

    - name: Enable PasswordAuthentication yes
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication.*'
        line: 'PasswordAuthentication yes'
        backup: no
      notify: reload sshd

    - name: Show ssh auth config
      command: grep -E "^(PermitRootLogin|PasswordAuthentication)" /etc/ssh/sshd_config
      register: ssh_auth_status
      ignore_errors: yes

    - name: Display ssh config lines
      debug:
        var: ssh_auth_status.stdout_lines


    - name: Set root password
      shell: echo "root:{{ root_password }}" | chpasswd
    
  handlers:
    - name: reload sshd
      service:
        name: ssh
        state: reloaded






- name: install python3 and python3-pip
  hosts: all
  become: yes
  gather_facts: no

  vars:
    AI_PATH = "/opt/ai_models"
  tasks:
    - name: Install python3 and python3-pip
      yum:
        name:
          - python3
          - python3-pip

    - name: create ai_models dir
      file:
        name: "{{ AI_PATH }}"
        state: directory
        mode: '0777'

    - name: install PyTorch via pip
      pip:
        name: PyTorch
        executable: pip3
      

      
- name: configure nopassword login for opsadmin
  hosts: all
  become: yes
  gather_facts: no

  vars:
    user: "opsadmin"
    group: "opsadmin"

  tasks:
  - name: create opsadmin user
    user: 
      name: "{{ user }}"
      password: "{{ 'Goodsense@123' | password_hash('sha512') }}"

  - name: configure ssh login
  # 直接使用神仙模块 authorized_key！它会自动帮你建 .ssh 目录，设好 0700 权限，并保证公钥只添加一次。
    authorized_key:
      user: "{{ user }}"
      state: present
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIxocYkl4MFvtYABklz9otY14QUeGrJdHc3MjMKPJCre pjlab\gongzhenglei@PJNL251080141W"

  # 使用 lineinfile 替代 sed
  - name: change sshd_config
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#?PermitRootLogin'
      line: 'PermitRootLogin no'
    notify: restart sshd service
    # shell: "sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config"

  - name: restart sshd service
    systemd:
      name: sshd
      state: restarted



- name: cron job to check gpu state
  host: all
  become: yes
  gather_facts: no

  vars:
    source_path: /home/test6/check_gpu_status.sh
    dest_path: /root/check_gpu_status.sh

  tasks:
  - name: create file
    copy:
      src: "{{ source_path }}"
      des: "{{ dest_path }}"
      mode: '0755'

  - name: create cron job to run the script
    cron:
      name: "run the gpu status script"
      minute: "10"
      hour: "0"
      job: "bash {{ dest_path }}"
      user: root
