- name: Enable root SSH and set root password
  hosts: all
  become: yes
  gather_facts: no

  vars:
    root_password: "Goodsense@123"

  tasks:
    - name: Configure SSH to allow root login and password auth
      replace:
        path: /etc/ssh/sshd_config
        regexp: '^#?(PermitRootLogin|PasswordAuthentication).*'
        replace: '\1 yes'
      notify: reload sshd

    - name: Set root password
      user:
        name: root
        password: "{{ root_password | password_hash('sha512') }}"
    
  handlers:
    - name: reload sshd
      service:
        name: ssh
        state: reloaded