apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: job-3878c6bf
  namespace: 07b5fca8-be94-4f26-b2a0-37df9bd552c3
  resourceVersion: "265869256"
  uid: f3800b49-8b99-4307-8170-cd740a33ce33
spec:
  backoffLimit: 0
  entrypoint: |-
    bash -c 'cd /mnt/hw/hw-linyifei2/nengx/xtuner_fork/xtuner
    sleep inf'
  rayClusterSpec:
    headGroupSpec:
      rayStartParams: {}
      template:
        metadata:
          namespace: 07b5fca8-be94-4f26-b2a0-37df9bd552c3
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: topology.sensecore.cn/boson-rdma-network-cluster
                    operator: In
                    values:
                    - None
                  - key: resource.compute.sensecore.cn/machine-type
                    operator: In
                    values:
                    - h2ls.ru.k10
                  - key: resource.compute.sensecore.cn/provide-spot-resource
                    operator: NotIn
                    values:
                    - "false"
          containers:
          - env:
            - name: SSP_TRAININGJOB_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['volcano.sh/job-name']
            image: registry2.d.pjlab.org.cn/ccr-hw/910c:rl_s1_vllm
            imagePullPolicy: Always
            name: head
            resources:
              limits:
                cpu: "256"
                huawei.com/Ascend910: "16"
                memory: 1920Gi
              requests:
                cpu: "256"
                huawei.com/Ascend910: "16"
                memory: 1920Gi
            securityContext:
              capabilities:
                add:
                - IPC_LOCK
                - SYS_PTRACE
            volumeMounts:
            - mountPath: /dev/shm
              name: ait-shm-volume
            - mountPath: /mnt/hw
              name: ait-pvc-0789258b-7583-42db-b56e-38dc391a036f-0
          nodeSelector:
            accelerator-type: module-910c-8
          restartPolicy: Never
          volumes:
          - emptyDir:
              medium: Memory
              sizeLimit: 1Ti
            name: ait-shm-volume
          - name: ait-pvc-0789258b-7583-42db-b56e-38dc391a036f-0
            persistentVolumeClaim:
              claimName: ait-pvc-0789258b-7583-42db-b56e-38dc391a036f-0
  shutdownAfterJobFinishes: true
  submissionMode: SidecarMode
  ttlSecondsAfterFinished: 0