apiVersion: v1
kind: Pod
metadata:
  name: job-632b40ff-hvqkn-head-mg59x
  namespace: 07b5fca8-be94-4f26-b2a0-37df9bd552c3
  ownerReferences:
  - apiVersion: ray.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: RayCluster
    name: job-632b40ff-hvqkn
    uid: 2eea8dc1-095b-4c96-b7ba-19a9a1d45c4e
  resourceVersion: "265520217"
  uid: b2e9eb98-865c-42d2-b15c-2ea2e3f3af58
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.sensecore.cn/boson-rdma-network-cluster
            operator: In
            values:
            - None
          - key: resource.compute.sensecore.cn/machine-type
            operator: In
            values:
            - h2ls.ru.k10
          - key: resource.compute.sensecore.cn/provide-spot-resource
            operator: NotIn
            values:
            - "false"
  containers:
  - args:
    - 'ulimit -n 65536; ray start --head  --block  --dashboard-agent-listen-port=52365  --dashboard-host=0.0.0.0  --memory=2061584302080  --metrics-export-port=8080  --num-cpus=256 '
    command:
    - /bin/bash
    - -c
    - --
    env:
    - name: SSP_TRAININGJOB_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels['volcano.sh/job-name']
    - name: RAY_CLUSTER_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels['ray.io/cluster']
    - name: RAY_CLOUD_INSTANCE_ID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: RAY_NODE_TYPE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels['ray.io/group']
    - name: KUBERAY_GEN_RAY_START_CMD
      value: 'ray start --head  --block  --dashboard-agent-listen-port=52365  --dashboard-host=0.0.0.0  --memory=2061584302080  --metrics-export-port=8080  --num-cpus=256 '
    - name: RAY_PORT
      value: "6379"
    - name: RAY_ADDRESS
      value: 127.0.0.1:6379
    - name: RAY_USAGE_STATS_KUBERAY_IN_USE
      value: "1"
    - name: RAY_USAGE_STATS_EXTRA_TAGS
      value: kuberay_version=v1.5.1;kuberay_crd=RayJob
    - name: RAY_DASHBOARD_ENABLE_K8S_DISK_USAGE
      value: "1"
    image: registry2.d.pjlab.org.cn/ccr-hw/910c:rl_s1_vllm
    imagePullPolicy: Always
    livenessProbe:
      exec:
        command:
        - bash
        - -c
        - wget --tries 1 -T 2 -q -O- http://localhost:52365/api/local_raylet_healthz
          | grep success && wget --tries 1 -T 10 -q -O- http://localhost:8265/api/gcs_healthz
          | grep success
      failureThreshold: 120
      initialDelaySeconds: 30
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    name: head
    ports:
    - containerPort: 8080
      name: metrics
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - bash
        - -c
        - wget --tries 1 -T 2 -q -O- http://localhost:52365/api/local_raylet_healthz
          | grep success && wget --tries 1 -T 10 -q -O- http://localhost:8265/api/gcs_healthz
          | grep success
      failureThreshold: 10
      initialDelaySeconds: 10
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: "256"
        huawei.com/Ascend910: "16"
        memory: 1920Gi
      requests:
        cpu: "256"
        huawei.com/Ascend910: "16"
        memory: 1920Gi
    securityContext:
      capabilities:
        add:
        - IPC_LOCK
        - SYS_PTRACE
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /dev/shm
      name: ait-shm-volume
    - mountPath: /mnt/hw
      name: ait-pvc-c9038450-3189-4e26-bb0f-dee6e0bb37f3-0
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-ddbgb
      readOnly: true
  - args:
    - until wget --tries 1 -T 10 -q -O- http://localhost:8265/api/gcs_healthz | grep
      success >/dev/null 2>&1 ; do echo "Waiting for Ray Dashboard GCS to become healthy
      at http://127.0.0.1:8265 ..." ; sleep 2 ; done ; ray job submit --address http://127.0.0.1:8265
      --submission-id job-632b40ff-6759j -- sleep inf ;
    command:
    - /bin/bash
    - -ce
    - --
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: RAY_DASHBOARD_ADDRESS
    - name: RAY_JOB_SUBMISSION_ID
      value: job-632b40ff-6759j
    image: registry2.d.pjlab.org.cn/ccr-hw/910c:rl_s1_vllm
    imagePullPolicy: IfNotPresent
    name: ray-job-submitter
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 200Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-ddbgb
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: host-10-140-216-206
  nodeSelector:
    accelerator-type: module-910c-8
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: volcano
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir:
      medium: Memory
      sizeLimit: 64Gi
    name: ait-shm-volume
  - name: ait-pvc-c9038450-3189-4e26-bb0f-dee6e0bb37f3-0
    persistentVolumeClaim:
      claimName: ait-pvc-c9038450-3189-4e26-bb0f-dee6e0bb37f3-0
  - name: kube-api-access-ddbgb
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace