kind: 'Job'
apiVersion: 'batch.volcano.sh/v1alpha1'
metadata:
  generateName: 'oc-api-api-eval-v4-171-zhaozhonghan-a3-23-'
  namespace: 'default'
  generation: 1
  creationTimestamp: '2026-04-24T07:14:50Z'
  labels:
    lepton.sensetime.com/framework-type: 'PyTorch'
    lepton.sensetime.com/submitter: 'xujun'
    ring-controller.atlas: 'ascend-910b'
  annotations:
    sp-block: '2'
  managedFields:
    - manager: 'OpenAPI-Generator'
      operation: 'Update'
      apiVersion: 'batch.volcano.sh/v1alpha1'
      time: '2026-04-24T07:14:50Z'
      fieldsType: 'FieldsV1'
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:sp-block: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:lepton.sensetime.com/framework-type: {}
            f:lepton.sensetime.com/submitter: {}
            f:ring-controller.atlas: {}
        f:spec:
          .: {}
          f:maxRetry: {}
          f:minAvailable: {}
          f:plugins:
            .: {}
            f:hcclrank: {}
            f:pytorch: {}
            f:svc: {}
          f:policies: {}
          f:priorityClassName: {}
          f:queue: {}
          f:schedulerName: {}
          f:tasks: {}
    - manager: 'vc-controller-manager'
      operation: 'Update'
      apiVersion: 'batch.volcano.sh/v1alpha1'
      time: '2026-04-24T07:15:24Z'
      fieldsType: 'FieldsV1'
      fieldsV1:
        f:status:
          .: {}
          f:conditions: {}
          f:controlledResources:
            .: {}
            f:plugin-pytorch: {}
            f:plugin-svc: {}
          f:minAvailable: {}
          f:running: {}
          f:state:
            .: {}
            f:lastTransitionTime: {}
            f:phase: {}
          f:taskStatusCount:
            .: {}
            f:worker:
              .: {}
              f:phase:
                .: {}
                f:Running: {}
      subresource: 'status'
spec:
  schedulerName: 'volcano'
  minAvailable: 1
  tasks:
    - name: 'worker'
      replicas: 1
      minAvailable: 1
      template:
        metadata:
          creationTimestamp: null
          labels:
            lepton.sensetime.com/submitter: 'xujun'
            ring-controller.atlas: 'ascend-910b'
        spec:
          volumes:
            - name: 'pvc-a3-llmit-shared'
              persistentVolumeClaim:
                claimName: 'pvc-a3-llmit-shared'
            - name: 'pvc-xujun'
              persistentVolumeClaim:
                claimName: 'pvc-xujun'
            - name: 'pvc-a3-weight-share'
              persistentVolumeClaim:
                claimName: 'pvc-a3-weight-share'
            - name: 'pvc-intern-delivery-shared'
              persistentVolumeClaim:
                claimName: 'pvc-intern-delivery-shared'
            - name: 'shm-data'
              emptyDir:
                medium: 'Memory'
                sizeLimit: '128Gi'
          containers:
            - name: 'worker'
              image: 'registry2.d.pjlab.org.cn/ccr-deeplink/lmdeploy_dlinfer:0.12.3rc'
              livenessProbe:
                httpGet:
                  path: /health
                  port: 48330
                timeoutSeconds: 10
                periodSeconds: 60
                failureThreshold: 3
              command:
                - 'bash'
                - '-c'
              args:
                - "export MASTER_ADDR=${MASTER_ADDR:-$HOSTNAME} && export MASTER_PORT=${MASTER_PORT:-6000} && export WORLD_SIZE=${WORLD_SIZE:-$NODE_COUNT} && export RANK=${RANK:-$NODE_RANK} && source /usr/local/Ascend/ascend-toolkit/set_env.sh && export LD_LIBRARY_PATH=/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/driver/lib64/common:$LD_LIBRARY_PATH && export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True && export MULTI_STREAM_MEMORY_REUSE=2 && export HCCL_RDMA_TC=132 && export HCCL_CONNECT_TIMEOUT=3600 && export HCCL_BUFFSIZE=512 && export TORCH_HCCL_ZERO_COPY=1 && export GPUS_PER_NODE=$(echo $ASCEND_VISIBLE_DEVICES | tr ',' '\n' | wc -l) && export GLOO_SOCKET_IFNAME=eth0 && export ASCEND_WORK_PATH=/tmp && sysctl -w net.ipv4.tcp_max_syn_backlog=65536 && sysctl -w net.core.somaxconn=65536 && sysctl -w net.ipv4.ip_local_reserved_ports=60000-60015 && bash /mnt/xujun/develops/clusterx-api/app/util/run_cmd.sh ZWNobyAkQVNDRU5EX1ZJU0lCTEVfREVWSUNFUyAmJiBleHBvcnQgQVNDRU5EX1JUX1ZJU0lCTEVfREVWSUNFUz0kKGVjaG8gJEFTQ0VORF9WSVNJQkxFX0RFVklDRVMgfCBzZWQgJ3MvQXNjZW5kOTEwLS8vZycgfCB0ciAnLCcgJCdcbicgfCBzb3J0IC1uIHwgcGFzdGUgLXNkLCAtKSAmJiBlY2hvICRBU0NFTkRfUlRfVklTSUJMRV9ERVZJQ0VTICYmIGV4cG9ydCBIQ0NMX0NPTk5FQ1RfVElNRU9VVD03MjAwO2V4cG9ydCBQWVRPUkNIX05QVV9BTExPQ19DT05GPSJleHBhbmRhYmxlX3NlZ21lbnRzOlRydWUiO2V4cG9ydCBIQ0NMX09QX0VYUEFOU0lPTl9NT0RFPSJBSVYiO2V4cG9ydCBIQ0NMX0JVRkZTSVpFPTUxMjtleHBvcnQgTERfUFJFTE9BRD0vdXNyL2xpYjY0L2xpYmplbWFsbG9jLnNvLjI6JExEX1BSRUxPQUQgJiYgbG1kZXBsb3kgc2VydmUgYXBpX3NlcnZlciAvbW50L2EzLWxsbWl0LXNoYXJlZC96aGFuZ3lpbWluZy9zaGFyZWQvbGxtL25wcC90cmFpbi9zMi1zZnQtdHAtYmFzZWxpbmUvczJfdHBfYmFzZWxpbmVfc2Z0LzIwMjYwMjI0MTI1NTM3L2hmLTI2NSAtLW1vZGVsLW5hbWUgczItdHAtYmFzZWxpbmUtc2Z0LWxjYnY2LTA0MjQgLS1zZXJ2ZXItcG9ydCA0ODMzMCAtLWxvZy1sZXZlbCBJTkZPIC0tYmFja2VuZCBweXRvcmNoIC0tZGV2aWNlIGFzY2VuZCAtLW1heC1iYXRjaC1zaXplIDI1NiAtLWNhY2hlLWJsb2NrLXNlcS1sZW4gMTI4IC0tY2FjaGUtbWF4LWVudHJ5LWNvdW50IDAuOSAtLXRwIDIgLS1kdHlwZSBiZmxvYXQxNiAtLXNlc3Npb24tbGVuIDY0MDAwIC0tbWF4LXByZWZpbGwtdG9rZW4tbnVtIDgxOTI="
              env:
                - name: 'JOB_NAME'
                  valueFrom:
                    fieldRef:
                      fieldPath: 'metadata.labels[''volcano.sh/job-name'']'
                - name: 'ASCEND_VISIBLE_DEVICES'
                  valueFrom:
                    fieldRef:
                      fieldPath: 'metadata.annotations[''huawei.com/Ascend910'']'
              resources:
                limits:
                  cpu: '64'
                  huawei.com/Ascend910: '2'
                  memory: '480Gi'
                requests:
                  cpu: '64'
                  huawei.com/Ascend910: '2'
                  memory: '480Gi'
              volumeMounts:
                - name: 'pvc-a3-llmit-shared'
                  mountPath: '/mnt/a3-llmit-shared'
                - name: 'pvc-xujun'
                  mountPath: '/mnt/xujun'
                - name: 'pvc-a3-weight-share'
                  mountPath: '/mnt/a3-weight-share'
                - name: 'pvc-intern-delivery-shared'
                  mountPath: '/mnt/intern-delivery-shared'
                - name: 'shm-data'
                  mountPath: '/dev/shm'
              imagePullPolicy: 'IfNotPresent'
              securityContext:
                capabilities:
                  add:
                    - 'IPC_LOCK'
                privileged: true
          restartPolicy: 'Never'
          nodeSelector:
            host-arch: 'huawei-arm'
          imagePullSecrets:
            - name: 'yehaochen-image-token1'
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: 'resource.compute.sensecore.cn/machine-type'
                        operator: 'In'
                        values:
                          - 'h2ls.ru.k10'
      maxRetry: 1
  policies:
    - action: 'RestartJob'
      event: 'PodEvicted'
    - action: 'TerminateJob'
      event: 'PodFailed'
  plugins:
    hcclrank: []
    pytorch:
      - '--master=master'
      - '--worker=worker'
      - '--port=23456'
    svc: []
  queue: 'default'
  maxRetry: 1
  priorityClassName: 'normal'
